source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'GraffiTab-iOS' do
    pod 'AFNetworking'
    pod 'ActionSheetPicker-3.0'
    pod 'MZFormSheetController'
    pod 'TPKeyboardAvoiding'
    pod 'SCLAlertView-Objective-C'
    pod 'iOS-Slide-Menu'
    pod 'HexColors'
    pod 'SlackTextViewController'
    pod 'AMAttributedHighlightLabel'
    pod 'ios-image-editor'
    pod 'XHTwitterPaggingViewer'
    pod 'SpinKit'
    pod 'MGSwipeTableCell'
    pod 'GLGroupChatPicView'
    pod 'TITokenField'
    pod 'GUITabPagerViewController'
    pod 'VGParallaxHeader'
    pod 'FXBlurView'
    pod 'EXPhotoViewer'
    pod 'TSClusterMapView'
    pod 'JPSThumbnailAnnotation'
    pod 'BlockAlertsAnd-ActionSheets'
    pod 'INSPullToRefresh'
    pod 'WYPopoverController'
    pod 'Reachability'
    pod 'ALAlertBanner'
    pod 'TWMessageBarManager'
    pod 'FBLikeLayout'
end